CREATE TABLE stats (id serial PRIMARY KEY, timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, data JSONB, hide BOOLEAN DEFAULT false);
CREATE TABLE devices (device_class VARCHAR(20) PRIMARY KEY, description TEXT);

